### ISSUE TITLE
No module named 'requests' when importing

### ISSUE THREAD

**Issue by paul-sud** [matecsaj/ebay_rest#28]
After I installed using the PyPI distribution with `poetry add ebay-rest==0.0.13`, I get an error trying to import `API`.

```
>>> from ebay_rest import API
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/paul/Library/Caches/pypoetry/virtualenvs/eggregator-6gqTu4MM-py3.9/lib/python3.9/site-packages/ebay_rest/__init__.py", line 1, in <module>
    from .a_p_i import API
  File "/Users/paul/Library/Caches/pypoetry/virtualenvs/eggregator-6gqTu4MM-py3.9/lib/python3.9/site-packages/ebay_rest/a_p_i.py", line 14, in <module>
    from .token import ApplicationToken, UserToken
  File "/Users/paul/Library/Caches/pypoetry/virtualenvs/eggregator-6gqTu4MM-py3.9/lib/python3.9/site-packages/ebay_rest/token.py", line 6, in <module>
    from requests import codes, post, Response
ModuleNotFoundError: No module named 'requests'
```

This was fixed by manually installing `requests` but it would be nice to include it in the package dependencies.

**Comment by matecsaj** [comment]
Paul, thank you for the recommendation.  

The file setup.cfg now contains the following section.

install_requires =
    certifi
    python_dateutil
    requests
    selenium
    six
    urllib3

You could run the following to get the new release and install any missing dependencies.
pip3 install --upgrade ebay_rest
