### ISSUE TITLE
Is the sell_stores API is available?

### ISSUE THREAD

**Issue by matecsaj** [matecsaj/ebay_rest#85]
eBay's openAPI file sell_stores_v1_oas3.json or the Swagger Code Generator currently has an issue.

This happens when I run generate-code.py.

> /home/matecsaj/PycharmProjects/ebay_rest/venv/bin/python /home/matecsaj/PycharmProjects/ebay_rest/scripts/generate_code.py 
> 2024-05-13 21:46:34,537 ERROR generate_code.py 44 run_command: [stderr]
> Exception in thread "Thread-0" java.lang.RuntimeException: Could not process operation:
>   Tag: class Tag {
>     name: store
>     description: null
>     externalDocs: null
> }
>   Operation: getStoreCategories
>   Resource: get /store/categories
>   Exception: Could not identify any oauth2 flow in api_auth
> 	at io.swagger.codegen.v3.DefaultGenerator.processOperation(DefaultGenerator.java:989)
> 	at io.swagger.codegen.v3.DefaultGenerator.processPaths(DefaultGenerator.java:889)
> 	at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:484)
> 	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:796)
> 	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:388)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> Caused by: java.lang.RuntimeException: Could not identify any oauth2 flow in api_auth
> 	at io.swagger.codegen.v3.generators.DefaultCodegenConfig.fromSecurity(DefaultCodegenConfig.java:2876)
> 	at io.swagger.codegen.v3.DefaultGenerator.processOperation(DefaultGenerator.java:979)
> 	... 5 more
> 
> 2024-05-13 21:46:34,538 ERROR generate_code.py 431 patch_generated: Can't open /home/matecsaj/PycharmProjects/ebay_rest/scripts/api_cache/sell_stores/sell_stores/api_client.py.
> 2024-05-13 21:46:34,540 ERROR generate_code.py 455 patch_generated: Can't open /home/matecsaj/PycharmProjects/ebay_rest/scripts/api_cache/sell_stores/sell_stores/rest.py.
> 2024-05-13 21:46:34,588 WARNING generate_code.py 698 get_requirements: The requirements for library sell_stores are unknown because a file is missing /home/matecsaj/PycharmProjects/ebay_rest/scripts/api_cache/sell_stores/setup.py.
> 
> Process finished with exit code 0

**Comment by matecsaj** [comment]
It is still in Beta, so wait it out.

https://developer.ebay.com/api-docs/sell/stores/overview.html

**Comment by matecsaj** [comment]
It’s still not working and still marked as beta, so let’s continue to wait.
