### ISSUE TITLE
Buy API: self._check_header, references/global_id_values.json is preventing valid requests

### ISSUE THREAD

**Issue by chapmanjacobd** [matecsaj/ebay_rest#88]
Compare these two tracebacks:

Unsupported marketplace which passes the `_check_header` function:

```
Traceback (most recent call last):
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/a_p_i_private.py", line 1009, in _call_swagger
    api_response = swagger_method(**kwargs)
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/api/buy_browse/api/item_summary_api.py", line 69, in search
    (data) = self.search_with_http_info(**kwargs)  # noqa: E501
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/api/buy_browse/api/item_summary_api.py", line 170, in search_with_http_info
    return self.api_client.call_api(
           ~~~~~~~~~~~~~~~~~~~~~~~~^
        '/item_summary/search', 'GET',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
        _request_timeout=params.get('_request_timeout'),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        collection_formats=collection_formats)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/api/buy_browse/api_client.py", line 316, in call_api
    return self.__call_api(resource_path, method,
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                           path_params, query_params, header_params,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
                           _return_http_data_only, collection_formats,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                           _preload_content, _request_timeout)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/api/buy_browse/api_client.py", line 148, in __call_api
    response_data = self.request(
        method, url, query_params=query_params, headers=header_params,
        post_params=post_params, body=body,
        _preload_content=_preload_content,
        _request_timeout=_request_timeout)
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/api/buy_browse/api_client.py", line 338, in request
    return self.rest_client.GET(url,
           ~~~~~~~~~~~~~~~~~~~~^^^^^
                                query_params=query_params,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                _preload_content=_preload_content,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                _request_timeout=_request_timeout,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                headers=headers)
                                ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/api/buy_browse/rest.py", line 230, in GET
    return self.request("GET", url,
           ~~~~~~~~~~~~^^^^^^^^^^^^
                        headers=headers,
                        ^^^^^^^^^^^^^^^^
                        _preload_content=_preload_content,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        _request_timeout=_request_timeout,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        query_params=query_params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/api/buy_browse/rest.py", line 224, in request
    raise ApiException(http_resp=r)
ebay_rest.api.buy_browse.rest.ApiException: (409)
Reason: Conflict
HTTP response headers: HTTPHeaderDict({'rlogid': '...', 'x-ebay-svc-tracking-data': '...', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'x-frame-options': 'DENY', 'Content-Type': 'application
/json', 'Content-Length': '560', 'x-envoy-upstream-service-time': '30', 'Server': 'ebay-proxy-server', 'x-ebay-pop-id': '...', 'Expires': 'Sun, 22 Dec 2024 15:49:01 GMT', 'Cache-
Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sun, 22 Dec 2024 15:49:01 GMT', 'Connection': 'keep-alive', 'x-CDN': 'Akamai', 'Strict-Transport-Security': 'max-age=3
1536000'})
HTTP response body: b'{"errors":[{"errorId":12019,"domain":"API_BROWSE","category":"REQUEST","message":"Currently, the EBAY-PH marketplace is not supported. The supported Marketplaces are: [EB
AY-GB, EBAY-DE, EBAY-US, EBAY-AU, EBAY-IT, EBAY-CA, EBAY-ES, EBAY-FR, EBAY-HK, EBAY-SG, EBAY-IE, EBAY-PL, EBAY-NL, EBAY-AT, EBAY-CH, EBAY-BE].","parameters":[{"name":"marketplaceId","value":"E
BAY-PH"},{"name":"allowedMarketplaces","value":"[EBAY-GB, EBAY-DE, EBAY-US, EBAY-AU, EBAY-IT, EBAY-CA, EBAY-ES, EBAY-FR, EBAY-HK, EBAY-SG, EBAY-IE, EBAY-PL, EBAY-NL, EBAY-AT, EBAY-CH, EBAY-BE]
"}]}]}'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/download.py", line 218, in <module>
    for data in update_data(api, marketplace_instructions):
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/download.py", line 79, in update_data
    for idx, d in enumerate(data):  # type: ignore
                  ~~~~~~~~~^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/a_p_i_private.py", line 676, in _method_paged
    result = self._call_swagger(
        swagger_method, params, kwargs, swagger_method_exception
    )
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/a_p_i_private.py", line 1015, in _call_swagger
    raise Error(number=99000 + e.status, reason=e.reason, detail=e.body)
ebay_rest.error.Error: Error number 99409. Conflict b'{"errors":[{"errorId":12019,"domain":"API_BROWSE","category":"REQUEST","message":"Currently, the EBAY-PH marketplace is not supported. The
 supported Marketplaces are: [EBAY-GB, EBAY-DE, EBAY-US, EBAY-AU, EBAY-IT, EBAY-CA, EBAY-ES, EBAY-FR, EBAY-HK, EBAY-SG, EBAY-IE, EBAY-PL, EBAY-NL, EBAY-AT, EBAY-CH, EBAY-BE].","parameters":[{"
name":"marketplaceId","value":"EBAY-PH"},{"name":"allowedMarketplaces","value":"[EBAY-GB, EBAY-DE, EBAY-US, EBAY-AU, EBAY-IT, EBAY-CA, EBAY-ES, EBAY-FR, EBAY-HK, EBAY-SG, EBAY-IE, EBAY-PL, EBA
Y-NL, EBAY-AT, EBAY-CH, EBAY-BE]"}]}]}'
```

Supported marketplace which does not pass the `_check_header` function:

```
Fetching EBAY_BE
Traceback (most recent call last):
  File "/app/download.py", line 206, in <module>
    api = setup_api(marketplace)
  File "/app/download.py", line 11, in setup_api
    api = API(
        application={
    ...<24 lines>...
        # timeout=50.0,
    )
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/multiton.py", line 48, in __call__
    return_object = super(Multiton, cls).__call__(*args, **kwargs)
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/a_p_i.py", line 145, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        path=path,
        ^^^^^^^^^^
    ...<7 lines>...
        async_req=async_req,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/a_p_i_private.py", line 227, in __init__
    self._check_header(header_keys_values)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/ebay_rest/a_p_i_private.py", line 529, in _check_header
    raise Error(
    ...<3 lines>...
    )
ebay_rest.error.Error: Error number 99009. Invalid header value. Header key marketplace_id has value EBAY_BE. Choose from EBAY_AT, EBAY_AU, EBAY_CH, EBAY_DE, EBAY_ENCA, EBAY_ES, EBAY_FR, EBAY_
FRBE, EBAY_FRCA, EBAY_GB, EBAY_HK, EBAY_IE, EBAY_IN, EBAY_IT, EBAY_MOTOR, EBAY_MY, EBAY_NL, EBAY_NLBE, EBAY_PH, EBAY_PL, EBAY_SG, EBAY_US.
```

---

After editing `references/global_id_values.json` to replace `EBAY_NLBE` with `EBAY_BE`, and using `EBAY_BE` instead of `EBAY_NLBE` as the marketplace_id in ebay_rest header kwarg, I get correct results:

BEFORE:

```
@ranch ~/diskprices> head -3 data/EBAY_NLBE.latest.jsonl | jq .item_web_url
"https://www.ebay.com/itm/365275800582"
"https://www.ebay.com/itm/155258880188?amdata=enc%3AAQAJAAAAoHoV3kP08IDx%2BKZ9MfhVJKmtKC7LZRjWUI%2Bj%2BuO3mXdpo6VoPkhKBkgiVko7ZbRFI4VZYGzy0dyKTThcHy7gohKAnJnayBJYBYWK2pvVonNaNCkpXOE70Gomyvol0abDrFL2VWqR0RcSLJp4jbj6FGo%2FdQVucUSiQiuf8Jvu24%2BCu%2BL%2ByTZXiu4hsrwJyQX8qUpGh%2BweCvK47cXaIacf%2BP4%3D"
"https://www.ebay.com/itm/116418593805"
```

AFTER:

```
@ranch ~/diskprices> head -3 data/EBAY_BE.staging.jsonl  | jq .item_web_url
"https://www.benl.ebay.be/itm/116399643744"
"https://www.benl.ebay.be/itm/365275800582"
"https://www.benl.ebay.be/itm/155258880188?amdata=enc%3AAQAJAAAAoHoV3kP08IDx%2BKZ9MfhVJKmtKC7LZRjWUI%2Bj%2BuO3mXdpo6VoPkhKBkgiVko7ZbRFIz4kBbNPKGyo833PmlfF5ahBAkqgMJ2xtkcGpMNPrjq%2Bq7FIonmURDnZsJipOYh7LQPQx6zlABzjUmqSu%2B%2B4JO%2F2fJ1Zff0QwrRrEWU2JW%2FNVrxX8Gs%2F8zUwuyoUQBV6LexuHjIrE3tnEbqfck91T5I%3D"
```

maybe `self._check_header` needs to reference `references/marketplace_id_values.json` instead?

thx

**Comment by matecsaj** [comment]
Hello Jacob @chapmanjacobd ,

I was unable to reproduce the issue you kindly reported. Please compare this [new unit test](https://github.com/matecsaj/ebay_rest/commit/2887b0f005f14928c2efb885703e9aab1b0432ac) to your code.

Thanks,
John

**Comment by chapmanjacobd** [comment]
hmm that's very strange. I wonder if the sandbox has different behavior? Are the item_web_url in the records starting with "https://www.benl.ebay.be" ? Might be good to add `item['item_web_url'].startswith("https://www.benl.ebay.be")` to the unit test

**Comment by matecsaj** [comment]
Per Jacob's suggestions, I [enhanced the unit tests for credentials and Belgium](https://github.com/matecsaj/ebay_rest/commit/4eac67de949f27f2427a3b6c4663dbf497cc9f21). However, the underlying problem remains.

**Comment by matecsaj** [comment]
Jacob, thanks for reporting a bug. The next release will include [this](https://github.com/matecsaj/ebay_rest/commit/74acbf2f780cbb3e5c4ec3dbdf08c61b93ea3d4b) fix.

**Comment by matecsaj** [comment]
I just published version 1.0.7 of ebay_rest which includes this fix. Use pip to update.
